name: Continuous Delivery

on: pull_request

jobs:
  build-package-and-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies required to build package
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # RELEASE_VERSION: ${{ github.ref_name }}
          RELEASE_VERSION: "TESTING"
